--Creating Doctors table
CREATE TABLE DOCTORS(SSN number(12)NOT NULL,
F_NAME VARCHAR(25),
L_NAME VARCHAR(25),
Speciality VARCHAR(50),
YearOfExpe NUMBER(4),CONSTRAINT PK_DOC_SSN PRIMARY KEY (SSN));


--Creating Patients table
CREATE TABLE PATIENTS(SSN Number(12) NOT NULL,
F_NAME VARCHAR(25),
L_NAME VARCHAR(25),
Primary_Physician_ID NUMBER(12),
ADDRESS VARCHAR2(200),
DOB date,CONSTRAINT PK_PATIENT_SSN PRIMARY KEY (SSN),CONSTRAINT FK_PRIM_PHYS_ID FOREIGN KEY (Primary_Physician_ID) REFERENCES DOCTORS(SSN));



--Creating Patients_History table
CREATE TABLE PATIENTS_HISTORY(SSN Number(12) NOT NULL,
F_NAME VARCHAR(25),
L_NAME VARCHAR(25),
Primary_Physician_ID NUMBER(12),
ADDRESS VARCHAR2(200),
DOB date);



--Creating Pharmacy table
CREATE TABLE PHARMACY(Pharmacy_id NUMBER(8) not null,
Name VARCHAR2(40),
Address VARCHAR2(200),
Phone_No NUMBER(10),CONSTRAINT PK_PHARMA_ID PRIMARY KEY (Pharmacy_id));


drop table pharmacy;

--Creating Pharma-Company table
CREATE TABLE PHARMA_COMPANY(PHARMA_COMPANY_ID number(8) not null,
Name VARCHAR2(40),
Address VARCHAR2(200),
Phone_No Number(10),
CONSTRAINT PK_PHARMA_COMPANY_ID PRIMARY KEY (PHARMA_COMPANY_ID));

Drop table drugs;

--Creating Drugs Table
CREATE TABLE DRUGS (DRUG_ID NUMBER(8) not null,
DRUG_TRADE_NAME VARCHAR2(50),
FORMULA VARCHAR2(200),
PRICE NUMBER(12,3),
PHARMA_COMPANY_ID NUMBER(8),
CONSTRAINT PK_DRUG_ID PRIMARY KEY (Drug_id),
CONSTRAINT FK_PHARMA_COMP_ID FOREIGN KEY (PHARMA_COMPANY_ID) REFERENCES PHARMA_COMPANY (PHARMA_COMPANY_ID) ON DELETE CASCADE);



--Creating Phrmacy Drugs Info Table
CREATE TABLE PHARMACY_DRUG_INFO (PHARMA_DRUG_ID NUMBER(8) NOT NULL,
DRUG_ID NUMBER(8),
PHARMACY_ID NUMBER(8),
QUANTITY NUMBER(8),
CONSTRAINT PK_PHARMA_DRUG_ID PRIMARY KEY (PHARMA_DRUG_ID),
CONSTRAINT FK_DRUG_ID FOREIGN KEY (DRUG_ID) REFERENCES DRUGS(DRUG_ID),
CONSTRAINT FK_PHARAMACY_ID FOREIGN KEY (PHARMACY_ID) REFERENCES PHARMACY(Pharmacy_id));



--Creating Prescriptions Table
CREATE TABLE PRESCRIPTIONS(PRESCRIPTION_ID NUMBER(8) NOT NULL,
Patient_id NUMBER(8),
Doctor_id NUMBER(8),
PHARMA_DRUG_ID NUMBER(8), 
Quantity NUMBER(8),
PRESCRIPTION_DATE Date,
CONSTRAINT PK_PRESCRIPTION_ID PRIMARY KEY (PRESCRIPTION_ID),
CONSTRAINT FK_PATIENT_ID FOREIGN KEY (Patient_id) REFERENCES PATIENTS(SSN),
CONSTRAINT FK_DOCTOR_ID FOREIGN KEY (Doctor_id) REFERENCES DOCTORS(SSN),
CONSTRAINT FK_PHARMA_DRUG_ID FOREIGN KEY (PHARMA_DRUG_ID) REFERENCES PHARMACY_DRUG_INFO(PHARMA_DRUG_ID));



--Creating Prescriptions_History Table
CREATE TABLE PRESCRIPTIONS_HISTORTY(PRESCRIPTION_ID NUMBER(8) NOT NULL,
Patient_id NUMBER(8),
Doctor_id NUMBER(8),
PHARMA_DRUG_ID NUMBER(8), 
Quantity NUMBER(8),
PRESCRIPTION_DATE Date);


--Creating Pharmacy_Sales Table
CREATE TABLE PHARMACY_SALES(PSID NUMBER(8) NOT NULL,
Sales_Date DATE,
Pharmacy_id Number(8),
Prescription_id NUMBER(8),
Amount NUMBER(10,3),
CONSTRAINT PK_PSID PRIMARY KEY (PSID),
CONSTRAINT FK_PHARMACY_ID FOREIGN KEY (Pharmacy_id) REFERENCES PHARMACY(Pharmacy_id),
CONSTRAINT FK_PRESCRIPTION_ID FOREIGN KEY (Prescription_id) REFERENCES PRESCRIPTIONS(PRESCRIPTION_ID));


--Creating Pharm_Company_Sales Table
CREATE TABLE PHARMA_COMPANY_SALES(PCSID NUMBER(8) NOT NULL,
Sales_Date DATE,
Pharmacy_id Number(8),
Drug_id NUMBER(8),
Quantity Number(8),
Amount NUMBER(8),
CONSTRAINT PK_PCSID PRIMARY KEY (PCSID),
CONSTRAINT FK_PHARMACY_ID_PCS FOREIGN KEY (Pharmacy_id) REFERENCES PHARMACY(Pharmacy_id),
CONSTRAINT FK_DRUG_ID_PCS FOREIGN KEY (Drug_id) REFERENCES DRUGS(DRUG_ID));


--Creating Contract Table
CREATE TABLE CONTRACT(CONTRACT_NO number(8) NOT NULL,
PHARMA_COMPANY_ID number(8),
Pharmacy_id number(8),
Start_Date date,
End_Date date,
Text_of_Contract varchar2(250),
CONSTRAINT PK_CONTRACT_NO PRIMARY KEY (CONTRACT_NO),
CONSTRAINT FK_PHARMACY_ID_CONTRACT FOREIGN KEY (Pharmacy_id) REFERENCES PHARMACY(Pharmacy_id),
CONSTRAINT FK_PHARMA_COMP_ID_CONTRACT FOREIGN KEY (PHARMA_COMPANY_ID) REFERENCES PHARMA_COMPANY (PHARMA_COMPANY_ID));


--Creating Supervisor Table
CREATE TABLE SUPERVISOR(SUPERVISOR_ID number(8) NOT NULL,
F_NAME VARCHAR(25),
L_NAME VARCHAR(25),
Pharmacy_id number(8),
CONTRACT_NO number(8),
CONSTRAINT PK_SUPERVISOR_ID PRIMARY KEY (SUPERVISOR_ID),
CONSTRAINT FK_PHARMACY_ID_SUPERVISOR FOREIGN KEY (Pharmacy_id) REFERENCES PHARMACY(Pharmacy_id),
CONSTRAINT FK_CONTRACT_NO FOREIGN KEY (CONTRACT_NO) REFERENCES CONTRACT(CONTRACT_NO));


--Creating Supervisor_History Table
CREATE TABLE SUPERVISOR_HISTORY(SUPERVISOR_ID number(8) NOT NULL,
F_NAME VARCHAR(25),
L_NAME VARCHAR(25),
Pharmacy_id number(8),
CONTRACT_NO number(8));